# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-22 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomments',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlecomments',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArticleComments',
        ),
    ]
